lista_alturas_heroes = [
    168,
    188,
    170.0,
    161.54,
    180.0,
    213.0,
    178.0,
    279.0,
    188.0,
    165,
    201.0,
    168.0,
    193.0,
    191.0,
    175.0,
    178.0,
    162,
    183.0,
    163,
    180,
    119000,
    198.0,
    183.0,
    177,
    178.0,
    165.0,
    185.0,
    168.0,
    191.0,
    165.0,
    188.0,
    267.0,
    175.0,
    183.0,
    188.0,
    168,
    168.0
]

lista_generos_heroes = [
    "Masculino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Femenino",
    "Femenino",
    "Masculino",
    "Femenino",
    "Masculino",
    "No-Binario",
    "Masculino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Femenino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Masculino",
    "Masculino"
]

lista_identidades_heroes = [
    "Delta Uno",
    "Cyberdyne Systems Series 800 Terminator Model 101",
    "Karen Beecher",
    "Benjamin Kirby Tennyson",
    "Kara Zor-L",
    "Yautja",
    "John Rambo",
    "Sauron",
    "Bruce Wayne",
    "Sara Lance",
    "Thanos",
    "Madelyne Jennifer Pryor",
    "Billy Batson",
    "Teth-Adam",
    "Saitama",
    "Narya",
    "Caitlin Snow",
    "Indiana Jones",
    "Mindy McCready",
    "Dave Lizewski",
    "Gojira",
    "Tony Stark",
    "John Constantine",
    "Faora Hu-Ul",
    "Carlos Ray Norris",
    "Dinah Drake Lance",
    "S'chn T'gai Spock",
    "Vegeta",
    "Eddie Brock",
    "Cassandra Elizabeth Sandsmark",
    "Steve Rogers",
    "Uxas",
    "Kakarot",
    "Han Solo",
    "John Hancock",
    "Harry James Potter",
    "Naruto Uzumaki"
]

lista_nombres_heroes = [
    "Jason Bourne",
    "T-800",
    "Bumblebee",
    "Ben 10",
    "Power Girl",
    "Predator",
    "Rambo",
    "Sauron",
    "Batman",
    "White Canary",
    "Thanos",
    "Goblin Queen",
    "Captain Marvel",
    "Black Adam",
    "One Punch Man",
    "Snowbird",
    "Killer Frost",
    "Indiana Jones",
    "Hit-Girl",
    "Kick-Ass",
    "Godzilla",
    "Iron Man",
    "John Constantine",
    "Faora",
    "Chuck Norris",
    "Black Canary",
    "Spock",
    "Vegeta",
    "Venom",
    "Wonder Girl",
    "Captain America",
    "Darkseid",
    "Goku",
    "Han Solo",
    "Hancock",
    "Harry Potter",
    "Naruto Uzumaki"
]

lista_poder_heroes = [
    26,
    73,
    47,
    90,
    100,
    100,
    30,
    100,
    47,
    49,
    100,
    65,
    100,
    100,
    55,
    70,
    59,
    19,
    27,
    22,
    100,
    100,
    54,
    98,
    42,
    45,
    56,
    100,
    86,
    39,
    60,
    100,
    100,
    43,
    100,
    100,
    100
]



